apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-db
  template:
    metadata:
      labels:
        app: oracle-db
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 54321:54321 /opt/oracle/oradata"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: oracle-data
              mountPath: /opt/oracle/oradata
      automountServiceAccountToken: false
      containers:
        - name: oracle-database
          image: container-registry.oracle.com/database/free:23.3.0.0
          ports:
            - containerPort: 1521
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
              ephemeral-storage: "2Gi"
            limits:
              memory: "4Gi"
              cpu: "2000m"
              ephemeral-storage: "5Gi"
          env:
            - name: ORACLE_PWD
              valueFrom:
                secretKeyRef:
                  name: cnpj-secrets
                  key: ORACLE_PASSWORD
            - name: APP_USER
              valueFrom:
                secretKeyRef:
                  name: cnpj-secrets
                  key: DB_USER
            - name: APP_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cnpj-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - mountPath: /opt/oracle/oradata
              name: oracle-data
      volumes:
        - name: oracle-data
          persistentVolumeClaim:
            claimName: oracle-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: oracle-service
spec:
  selector:
    app: oracle-db
  ports:
    - protocol: TCP
      port: 1521
      targetPort: 1521